baseURL: "https://kyrem1.github.io/"
title: "James Harbour"
paginate: 5
theme: "PaperMod"
publishDir: "docs"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: "UA-123-45"

pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true


params:
  env: "production"
  title: "James Harbour"
  description: "James Harbour's website"
  keywords: [ "math", "mathematics", "operator algebras", "analysis", "noncommutative geometry"]
  author: "James Harbour"
    # images: [ "<link or path of image for opengraph, twitter-cards>" ]

  math: true

  DateFormat: '2006-01-02'

  defaultTheme: "light"
  disableThemeToggle: true

  ShowBreadCrumbs: true

  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true

  showtoc: true
  tocopen: true
  UseHugoToc: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true


  ShowCodeCopyButtons: false
  ShowWordCount: true

  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false

  hidemeta: false
  hideSummary: false

  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
      #  safari_pinned_tab: "favicon-32x32.png"

  label:
    text: "James Harbour"
    icon: "/img/guraltsev-2glasses.jp"
      #  icon: "/favicon/apple-icon.png"
    iconHeight: 48

  profileMode:
    enabled: false
    title: "James Harbour"
    subtitle: ""
    imageUrl: "/img/guraltsev-1x1.jpg"
    imageWidth: 400
    imageHeight: 400
    imageTitle: "my image"

    # buttons:
    # - name: "Posts"
    #   url: "posts"
    # - name: "Tags"
    #   url: "tags"

    # homeInfoParams:
    #    Title: "James Harbour"
    #    Content: "Sophomore studying Math and CS - UVA"

  socialIcons:
    - name: "cv"
      url: "https://github.com/kyrem1/james2022cv/blob/b6e14c89be602015f823ab3f722b46bf5b64ff73/mathCVcurrent/cv2022.pdf"

    - name: "github"
      url: "https://github.com/kyrem1"

    - name: "email"
      url: "mailto:james.h.harbour@gmail.com"

    # name: "arXiv"
    # url: "https://arxiv.org/a/________.html"

    # name: "googlescholar"
    # url: "https://scholar.google.com/citations?user=MyoBqN8AAAAJ"

    # name: "stackoverflow"
    # url: "https://stackoverflow.com"


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/kyrem1/kyrem1.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"] 


menu:
  main:
    #- identifier: "Research"
    #  name: "Research"
    #  url: "research"
    #  weight: 10

    #- identifier: "Publications"
    #  name: "Publications"
    #  url: "publications"
    #  weight: 20


    - identifier: "Talks and Travel"
      name: "Talks and travel"
      url: "talks-travel"
      weight: 1

    #- identifier: "Teaching"
    #  name: "Teaching"
    #  url: "teaching"
    #  weight: 40

    - identifier: "Other"
      name: "Other"
      url: "other"
      weight: 2


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
